### ISSUE TITLE
bug: star exports not in metadata

### ISSUE THREAD

**Issue by y-nk** [jordimarimon/ts-ast-parser#197]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/jordimarimon/ts-ast-parser/blob/main/CONTRIBUTING.md).
- [X] I have searched for [existing issues](https://github.com/jordimarimon/ts-ast-parser/issues) that already report this problem, without success.

### Version

latest

### Current Behavior

star exports are not parsed/counted in metadata

### Expected Behavior

we should have a `exports: [{ type: 'star' }]` if a star export is analyzed

### Steps to Reproduce

1. Create a lib file: `echo 'export function foo() {}' > ./libFile'`
2. Create a barrel file: `echo 'export * from './libFile' > ./barrelFile'`
3. Read the barrel file metadata: `console.log(parseFromFiles('./barrelFile'))`

**Comment by jordimarimon** [comment]
You're totally right!

My bad, I though I was already reflecting namespace exports. I think I have already fixed, I will release a new version in the following days.

Here you can have a look at how it will be reflected these types of exports:

**Input file:** 

https://github.com/jordimarimon/ts-ast-parser/blob/fb9770ae16e43d916f1453245bf68531214d3132/tests/export/namespace/index.ts

**Reflected data:**

https://github.com/jordimarimon/ts-ast-parser/blob/fb9770ae16e43d916f1453245bf68531214d3132/tests/export/namespace/output.json

If you find anything missing or you think there could be a better way to reflect this type of information, just let me know!

Thanks!

**Comment by y-nk** [comment]
Thanks a lot @jordimarimon 🙏
