### ISSUE TITLE
bug: required is not definded 

### ISSUE THREAD

**Issue by cleverboy32** [jordimarimon/ts-ast-parser#207]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/jordimarimon/ts-ast-parser/blob/main/CONTRIBUTING.md).
- [X] I have searched for [existing issues](https://github.com/jordimarimon/ts-ast-parser/issues) that already report this problem, without success.

### Version

0.5.0

### Current Behavior

in  node version 16, has error  required is not definded 

### Expected Behavior

//

### Steps to Reproduce

in node 16 ,run  this npm api

### Additional Information

![image](https://github.com/jordimarimon/ts-ast-parser/assets/17595456/98af4a33-deb0-48df-b351-1843715ed12d)

by this way, the problem is fixed
![image](https://github.com/jordimarimon/ts-ast-parser/assets/17595456/9ce0ee81-7107-4310-ac32-75d189d803ba)

**Comment by jordimarimon** [comment]
Hi!

Thanks for opening an issue. It has been fixed in the main branch!

In the next release the fix will be available. I'm planning on releasing the new version in two weeks (I want to solve #205 before the next release).

Thanks!
