### ISSUE TITLE
bug: `import {type XXX}` is not recognized as `typeOnly`

### ISSUE THREAD

**Issue by Lukinoh** [jordimarimon/ts-ast-parser#209]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/jordimarimon/ts-ast-parser/blob/main/CONTRIBUTING.md).
- [X] I have searched for [existing issues](https://github.com/jordimarimon/ts-ast-parser/issues) that already report this problem, without success.

### Version

@ts-ast-parser/core@0.6.1

### Current Behavior

When parsing code that uses `import {type XXX} from 'moduleName'` the `typeOnly` for the corresponding named import is not defined.

### Expected Behavior

I would expect that the `typeOnly` is set to `true`.

### Steps to Reproduce

Use the following snippet in https://jordimarimon.github.io/ts-ast-parser/playground/

```typescript
import {Toto} from 'module-name';
import type {TotoType} from 'module-name';
import {type TotoType, Toto} from 'module-name';
```

You can see that `TotoType` is not recognized as `typeOnly`.

In the [TypeScript AST Viewer](https://ts-ast-viewer.com/#code/JYWwDg9gTgLgBAbwCoRhAvnAZlCI4DkIEAJgK4A2ApgLQB2AhiFQQNwBQokscMAnmCqIUaJAKqYceQsXLV6TFhy7R4CfoLgiIYwQBotqDNlz4ipSrUbM27IA), it is correctly identified as `typeOnly`.

![image](https://github.com/jordimarimon/ts-ast-parser/assets/2392459/a6991f51-74c2-497a-aae1-02ca3731f2ba)

**Comment by jordimarimon** [comment]
Hi @Lukinoh!

Thanks for opening an issue. You're totally right and it has been fixed.

The fix will be available in the next release.

Thanks!
