### ISSUE TITLE
bug: Fails to parse external modules when using `pnpm`

### ISSUE THREAD

**Issue by mikestopcontinues** [jordimarimon/ts-ast-parser#211]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/jordimarimon/ts-ast-parser/blob/main/CONTRIBUTING.md).
- [X] I have searched for [existing issues](https://github.com/jordimarimon/ts-ast-parser/issues) that already report this problem, without success.

### Version

0.6.3

### Current Behavior

When using `pnpm`, I receive errors like `Module '"playwright"' has no exported member 'Browser'.`

### Expected Behavior

It should work with `pnpm`.

### Steps to Reproduce

1. Load the repro URL
2. `pnpm install`
3. `pnpm start`

If you instead use `npm`, the repro will work correctly.

### Code Reproduction URL

https://stackblitz.com/edit/ts-ast-parser-vs-pnpm?file=src%2Findex.ts&view=editor

**Comment by jordimarimon** [comment]
This seems like a bug on my part. I will investigate and see if I can find a fix!
