### ISSUE TITLE
feat: `is.[TYPE]` should not require `ReflectedRootNode`

### ISSUE THREAD

**Issue by mikestopcontinues** [jordimarimon/ts-ast-parser#212]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/jordimarimon/ts-ast-parser/blob/main/CONTRIBUTING.md).
- [X] I have searched for [existing issues](https://github.com/jordimarimon/ts-ast-parser/issues) that already report this problem, without success.

### Describe the Feature Request

The `is` method signatures should be:

```ts
is.TypeAliasNode = (n: unknown) => n is TypeAliasNode
```

### Describe the Use Case

This would simplify working with `null` or `undefined` values, which many methods return.

**Comment by jordimarimon** [comment]
That would be a nice enhancement to the API. I will see what I can do!

**Comment by mikestopcontinues** [comment]
Thanks for being so responsive! This project is a gem.
