### ISSUE TITLE
bug: Does not install on Node 21

### ISSUE THREAD

**Issue by juho** [jordimarimon/ts-ast-parser#216]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/jordimarimon/ts-ast-parser/blob/main/CONTRIBUTING.md).
- [X] I have searched for [existing issues](https://github.com/jordimarimon/ts-ast-parser/issues) that already report this problem, without success.

### Version

0.7.0

### Current Behavior

```
pnpm add -D @ts-ast-parser/core
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

This error happened while installing a direct dependency of /Users/jh/dev/a70/aui

Your Node version is incompatible with "registry.npmjs.org/@ts-ast-parser/core/0.7.0".

Expected version: ^18.0.0 || ^20.0.0
Got: v21.6.1

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
```

### Expected Behavior

To install on node 21

### Steps to Reproduce

Install node 21
Install ts-ast-parser

**Comment by jordimarimon** [comment]
Hi!

Thanks for opening an issue. 

I normally don't support non LTS versions of Node but I suppose it doesn't hurt to enable support for 21.x.

I have released a new version (`0.8.0`).
